openapi: 3.0.1
info:
  title: playwright-aws-lambda
  description: >-
    Support for running Microsoft's Playwrite on AWS Lambda and Google Cloud
    functions
  x-cortex-git:
    github:
      repository: JupiterOne/playwright-aws-lambda
  x-cortex-owners:
    - type: group
      name: JupiterOne/Apps
  x-cortex-tag: playwright-aws-lambda
  x-cortex-service-groups:
    - tier-4
